apiVersion: v2
description: A Helm chart to provide an opinionated deployment of Sandboxed Containers in a validated pattern
keywords:
- pattern
- sandboxed-containers
- confidential-computing
- confidential-containers
name: sandboxed-containers
version: 0.2.0  
